---
'title: "Data Scraping 4B"
author: "Kathirmani Sukumar"
date: "9/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RJSONIO)
url_d1 = "https://raw.githubusercontent.com/skathirmani/datasets/master/json/d1.json"
d1 = RJSONIO::fromJSON(url_d1)
d1
class(d1)
length(d1)
```

```{r}
url_d3 = "https://raw.githubusercontent.com/skathirmani/datasets/master/json/d3.json"
d3 = RJSONIO::fromJSON(url_d3)
d3
length(d3)
d3[[2]]
```

```{r}
for (person in d3){
  print (person$role)
}
```


```{r}
summary = data.frame(name=c(),
                     class=c(),
                     role=c())
for (person in d3){
  curr_row = list(name = person$name, class=person$class, role=person$role)
  summary = rbind(summary, curr_row, stringsAsFactors=FALSE)
}
summary
```

```{r}
write.csv(summary, '/datasets/summary_test.csv', row.names = F)
```



```{r}
url_goog_repo = "https://api.github.com/orgs/google/repos"
repos = RJSONIO::fromJSON(url_goog_repo)
length(repos)
repos[[1]]$name
repos[[1]]$language
```

```{r}
library(httpuv)  
library(httr)
myapp <- oauth_app(appname = "scraping4b",
                   key = "Iv1.5d776bdbe65cdb11",
                   secret = "5abd31659ac0ea17e05fc193e81064601c4cc1c8")

github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
```

```{r}
url_goog_repo = "https://api.github.com/orgs/google/repos"
response = GET(url_goog_repo, github_token)
repos = content(response)
length(repos)
```



```{r}
df_repos = data.frame(id=c(), name=c(), 
                      stars=c(), created_at=c())
for (repo in repos){
  curr_row = list(id=repo$id, name=repo$name,
                  stars=repo$stargazers_count, created_at=repo$created_at)
  df_repos = rbind(df_repos, curr_row, stringsAsFactors=F)
}
df_repos
```

